// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoviesAPI.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MoviesAPI.Data.Migrations
{
    [DbContext(typeof(MoviesDbContext))]
    [Migration("20220418155941_UpdatedNameColumnToBeRequriedInGenre")]
    partial class UpdatedNameColumnToBeRequriedInGenre
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MoviesAPI.Entities.GenreEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3ae09852-d426-4782-8737-e062a814394f"),
                            Name = "Action"
                        },
                        new
                        {
                            Id = new Guid("8064cf6c-e113-4144-9ac7-1b9f540397fc"),
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = new Guid("36c6a9fe-a54c-46eb-8f0f-0b9a584864d3"),
                            Name = "Drama"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
